#!/bin/bash
# svn commit type = all, add, modify, delete

CURRENT_PATH=$(dirname $0)
CONFIG_FILE=${CURRENT_PATH}/config
if [ ! -e $CONFIG_FILE ]; then
	echo "no config file. please make config file"
	exit 1
fi

. $CONFIG_FILE

COMMIT_TYPE=$1
COMMIT_PATH=$2
COMMIT_ID=$3
COMMIT_MESSAGE_FILE=""

if [[ "add" != $COMMIT_TYPE ]] && [[ "modify" != $COMMIT_TYPE ]] && [[ "delete" = $COMMIT_TYPE ]] && [[ "all" = $COMMIT_TYPE ]]; then
	echo "not support commit_type"
	exit 1
fi

if [[ "" != $COMMIT_PATH ]] && [[ "" != $COMMIT_ID ]]; then
	if [ ! -e ${GIT_PATH}/${COMMIT_PATH} ]; then
		echo "not exists git path : ${COMMIT_PATH}"
		exit 1
	fi

	cd ${GIT_PATH}/${COMMIT_PATH}

	COMMIT_MESSAGE_FILE=${TMP_PATH}/${COMMIT_ID}
	eval "git log --pretty=%B -n 1 ${COMMIT_ID} > ${COMMIT_MESSAGE_FILE}"

	if [[ "add" = $COMMIT_TYPE ]] || [[ "modify" = $COMMIT_TYPE ]] || [[ "delete" = $COMMIT_TYPE ]]; then
		eval "sed '1s/$/ \#${COMMIT_TYPE}/' ${COMMIT_MESSAGE_FILE} > ${COMMIT_MESSAGE_FILE}.modify"
		eval "mv ${COMMIT_MESSAGE_FILE}.modify ${COMMIT_MESSAGE_FILE}"
	fi
else
	echo "enter commit message"
	read COMMIT_MESSAGE

	if [[ "" = $COMMIT_MESSAGE ]]; then
		echo "no commit message!!!"
		exit 1
	fi

	COMMIT_MESSAGE_FILE=${TMP_PATH}/${COMMIT_TYPE}
	eval "echo '${COMMIT_MESSAGE}' > ${COMMIT_MESSAGE_FILE}"
fi

cd $SVN_PATH

if [[ "all" = $COMMIT_TYPE ]] || [[ "add" = $COMMIT_TYPE ]]; then
	echo "svn add new files"
	FILES=$(svn st | grep '^?' | sed 's/^? *//')
	if [ "$FILES" != "" ]; then
		eval "svn st | grep '^?' | sed 's/^? *//' | xargs svn add"
	fi
	if [ "$FILES" = "" ]; then
		FILES=$(svn st | grep '^A' | sed 's/^A *//')
	fi
fi
if [[ "modify" = $COMMIT_TYPE ]]; then
	FILES=$(svn st | grep '^M' | sed 's/^M *//')
fi
if [[ "all" = $COMMIT_TYPE ]] || [[ "delete" = $COMMIT_TYPE ]]; then
	echo "svn remove deleted files"
	FILES=$(svn st | grep '^!' | sed 's/^! *//')
	if [ "$FILES" != "" ]; then
		eval "svn st | grep '^!' | sed 's/^! *//' | xargs svn rm --force"
	fi
	if [ "$FILES" = "" ]; then
		FILES=$(svn st | grep '^D' | sed 's/^D *//')
	fi
fi

if [[ "all" = $COMMIT_TYPE ]]; then
	eval "svn commit -F ${COMMIT_MESSAGE_FILE}"
else
	if [ "$FILES" != "" ]; then
		if [[ "add" = $COMMIT_TYPE ]]; then
			eval "svn st | grep '^A' | sed 's/^A *//' | xargs svn commit -F ${COMMIT_MESSAGE_FILE}"
		fi
		if [[ "modify" = $COMMIT_TYPE ]]; then
			eval "svn st | grep '^M' | sed 's/^M *//' | xargs svn commit -F ${COMMIT_MESSAGE_FILE}"
		fi
		if [[ "delete" = $COMMIT_TYPE ]]; then
			eval "svn st | grep '^D' | sed 's/^D *//' | xargs svn commit -F ${COMMIT_MESSAGE_FILE}"
		fi
	else
		echo "no commit files!!"
	fi
fi

rm $COMMIT_MESSAGE_FILE

cd $CURRENT_PATH
echo "complete"
