#!/bin/bash
CMD=$1

CURRENT_PATH=$(dirname $0)
CONFIG_FILE=${CURRENT_PATH}/config
if [ -e $CONFIG_FILE ]; then
    . $CONFIG_FILE
fi

# composer update and composer.lock file copy from svn to git folder
if [ "composer" = $CMD ]; then
	UPDATE_PATH=$2
	PACKAGE=""
	if ["" != $3]; then
		PACKAGE=$3
	fi

	COMPOSER_PATH=$(command -v "composer")
	if [ "" = $COMPOSER_PATH ]; then
		echo "not installed composer"
		exit 1
	fi

	COMPOSER_FLAGS="--no-dev --optimize-autoloader"

	UPDATE_COMPOSER_COMMAND="composer update ${COMPOSER_FLAGS} ${PACKAGE}"
	INSTALL_COMPOSER_COMMAND="composer install ${COMPOSER_FLAGS}"

	SVN_COMPOSER_PATH=${SVN_PATH}/${UPDATE_PATH}
	GIT_COMPOSER_PATH=${GIT_PATH}/${UPDATE_PATH}

	echo "update composer - svn"
	cd $SVN_COMPOSER_PATH
	eval $UPDATE_COMPOSER_COMMAND

	echo "copy composer.lock"
	eval "cp -f ${SVN_COMPOSER_PATH}/composer.lock ${GIT_COMPOSER_PATH}/composer.lock"

	echo "install composer - git"
	cd $GIT_COMPOSER_PATH
	eval $INSTALL_COMPOSER_COMMAND

	cd $CURRENT_PATH
	echo "complete"
fi

# git to svn - memory commit message
# svn commit type = all, add, modify, delete
# svn rollback & commit